# ansible-playbook -l node4 playbooks/colorprompt.yaml -e "color=33"
- name: Change prompt color in bashrc
  hosts: all
  gather_facts: false
  tasks:
    - name: Change prompt color in bashrc
      ansible.builtin.lineinfile:
        path: /home/rc/.bashrc
        regexp: '^export PS1='
        line: 'export PS1="\e[0;{{ color | default("31") }}m[\u@\h \W]\$ \e[m "'
        state: present
      become: true
