---
- name: Change prompt color in bashrc
  hosts: all
  vars_prompt:
    - name: color
      prompt: "Enter a color (30->Black, 31->Red, 32->Green, 33->Yellow, 34->Blue, 35->Magenta, 36->Cyan, 37->White)"
      private: false
  tasks:
    - name: Change prompt color in bashrc
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        regexp: '^export PS1='
        line: 'export PS1="\e[0;{{ color | default("33") }}m[\u@\h \W]\$ \e[m "'
        state: present
      become: true
