- name: Change prompt color in bashrc
  hosts: all
  tasks:
    - name: Change prompt color in bashrc
      ansible.builtin.lineinfile:
        path: /home/rc/.bashrc
        regexp: '^export PS1='
        line: 'export PS1="\e[0;33m[\u@\h \W]\$ \e[m "'
        state: present
      become: true
