---
- name: Copy /etc/hosts
  hosts: all
  tasks:
    - name: Copy hosts file to remote hosts
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: /etc/hosts
        mode: "0644"
        backup: true
        force: true
      become: true
