---
- name: Copy files
  hosts: all
  vars_files:
    - ../variables.yaml
  tasks:
    - name: Copy hosts file to remote hosts
      ansible.builtin.copy:
        src: "{{ dir }}/hosts"
        dest: /etc/hosts
        mode: "0644"
        backup: true
        force: true
      become: true

    - name: Copy private key to all hosts
    # Want to copy private key (./keys/id_rsa) to all hosts so they can ssh into each other as well.
      ansible.builtin.copy:
        src: "{{ dir }}/keys/id_rsa"
        dest: /home/rc/.ssh
        backup: true
        mode: "0700"
