---
- name: Dnf install
  hosts: all
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install | default([]) }}"
