---
- name: Change hostname
  hosts: all
  become: true
  tasks:
    - name: Change hostname
      ansible.builtin.hostname:
        name: "{{ hostname | default(hostname) }}"
      when: hostname is defined
