- name: Get network configuration for all interfaces that are up
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Display network configuration
      ansible.builtin.debug:
        msg: |
          **Network Info**: {{ ansible_default_ipv4 }}
          **DNS Servers**: {{ ansible_dns.nameservers | join(', ') }}
