---
- name: Converting DHCP IP to a Static IP
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Converting DHCP IP to a Static IP
      ansible.builtin.debug:
        msg: "New Static IP: {{ ip_address | default(ansible_default_ipv4.address) }} | Old IP: {{ ansible_default_ipv4.address }}"

    - name: Add an Ethernet connection with static IP configuration
      community.general.nmcli:
        conn_name: "{{ conn_name | default(ansible_default_ipv4.alias) }}"
        ifname: "{{ ifname | default(ansible_default_ipv4.interface) }}"
        type: ethernet
        ip4: "{{ ip_address | default(ansible_default_ipv4.address) }}"
        gw4: "{{ gw_address | default(ansible_default_ipv4.gateway) }}"
        dns4: "{{ dns_servers | default('8.8.8.8,1.1.1.1') }}"
        state: present

    - name: Bring up network connection using nmcli
      ansible.builtin.command: nmcli connection up "{{ ansible_default_ipv4.alias }}"
      register: my_output # <- Registers the command output.
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
