---
- name: Add lines to message of the day (motd)
  hosts: all
  become: true
  tasks:
    - name: Set up welcome message
      ansible.builtin.lineinfile:
        path: /etc/motd
        line: "{{ motd | default('Savvy!') }}"
        state: present
