---
- name: Change hostname
  hosts: all
  become: true
  vars_files:
    - ../vars_subscription.yaml
    - ../variables.yaml
  tasks:
    - name: Change hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
