---
- name: Copy SSH public key to remote host
  hosts: all
  become: true
  gather_facts: false
  vars:
    remote_user: "rc"
    ssh_key_path: "/Users/arslankhan/.ssh/id_rsa.pub"

  tasks:
    - name: Ensure SSH public key is present
      ansible.builtin.stat:
        path: "{{ ssh_key_path }}"
      register: ssh_key_stat

    - name: Copy SSH public key to remote host
      ansible.builtin.copy:
        src: "{{ ssh_key_path }}"
        dest: "/home/{{ remote_user }}/authorized_keys"
        mode: "0644"
        backup: true
        force: true

    - name: Add SSH public key to authorized_keys
      # Use shell with >> , command gives error
      ansible.builtin.shell: "cat /home/{{ remote_user }}/authorized_keys >> /home/{{ remote_user }}/.ssh/authorized_keys"
      register: my_output
      changed_when: false

    - name: Remove temporary authorized_keys file
      ansible.builtin.file:
        path: "/home/{{ remote_user }}/authorized_keys"
        state: absent
