---
- name: Change hostname
  hosts: all
  become: true
  vars_files:
    - ../vars_subscription.yaml
  tasks:
    - name: Registering machine and attaching 'Employee SKU'
      community.general.redhat_subscription:
        state: present
        username: "{{ rh_username }}"
        password: "{{ rh_password }}"
        pool_ids: "{{ subscription_pool_id }}"
