- name: Registering machine and attaching 'Employee SKU'
  community.general.redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password }}"
    pool_ids: "{{ subscription_pool_id }}"
